### ISSUE TITLE
Django Channels Unresolved Import channels.generic.websockets

### ISSUE THREAD

**Issue by ian13456** [graphql-python/graphql-ws#30]
* GraphQL AioWS version: Django 2.1.5
* Python version: Python 3.6.6 :: Anaconda, Inc.
* Operating System: macOS Mojave 10.14

### Description

I'm trying to set up GraphQL Subscriptions with Django Channels 2, but the code keeps on throwing this error:
ModuleNotFoundError: No module named 'channels.generic.websockets'

### What I Did
I checked the Django Channels docs and also the source code of graphql_ws and figured a typo:
In the first line of django_channels.py, instead of 
```python
from channels.generic.websockets import JsonWebsocketConsumer
```
should be
```python
from channels.generic.websocket import JsonWebsocketConsumer
```
reference: https://channels.readthedocs.io/en/latest/topics/consumers.html#jsonwebsocketconsumer

```
python manage.py runserver
```

**Comment by Manviel** [comment]
I have an error
from django.db import close_old_connections
ModuleNotFoundError: No module named 'django.db'

**Comment by dvfcfbgv** [comment]
I switched to using https://github.com/datadvance/DjangoChannelsGraphqlWs because graphql-ws wasn't working for me. Note that DjangoChannelsGraphqlWs doesn't work for python 3.6 so what I did was I modified the source code.

**Comment by ryou90** [comment]
Here is the link to the related discussion about the future and maintainance of this project:
[graphql-python/graphene/issues/884]

**Comment by gotexis** [comment]
@dvfcfbgv I am facing the same issue. So did you mean you fixed the typo and got it to work, or you switched to DjangoChannelsGraphqlWs and then made some changes to make it work...

I have hit so many barriers implementing GraphQL + Django + VueJS,  that right now I am even thinking of just move on to Node.js... The stack would have many more readily available recipes

**Comment by dvfcfbgv** [comment]
I tried using graphql-ws but it didn't work, so I switched to using DjangoChannelsGraphqlWs. However DjangoChannelsGraphqlWs is written strictly for python3.7+, so I modified the source code to using python3.6. I'm currently using node.js prisma and reactjs for my project since django took too long to implement.

**Comment by gotexis** [comment]
Well at least I got that part right, switching to Node....

HAHAHAHA..

**Comment by gotexis** [comment]
@dvfcfbgv 
Hey I just followed you can saw your repository of a messenger in Django / react. Great, before switching to Vue I tried to do the same thing with that stack, before I find Vue more lovable.

Since I feel that we are on the same page, would you mind if I ask you to share your experience in implementing GraphQL in the backend. Opinions from the perspective from a Django background are scarce these days.

I just researched Prisma a bit and found it super cool. It has more stars than Apollo yet fewer downloads.

To give up on on Django-graphene, I have looked at so many unfamiliar things, including:

- Apollo server  (Most used overall, but I found it not abstracted)
- Strapi  (seems more abstracted, though have to use Koa2)
- Prisma  (seems abstracted to me as well)
- others I cannot recall...

Surely, Django has super high abstraction level and heavy reliance on opinions and ready recipes, which suits my needs very well. The generic class-based views really made development speed on steroids - last time, I made a small enterprise admin site in 3 days.

So as switching to Node, since I am currently just a one-man army, I really would prefer the possibility to write less code and get more magic.

What would you recommend in this case ;)

Thanks

**Comment by dvfcfbgv** [comment]
Hi @gotexis! 

I used Django and Graphene for my messenger clone app because I planned on implementing machine learning algorithms to the app somehow, and I figured the ML community in python is way more developed in Python. I like the fact that with Graphene, I get to design almost everything by myself. I also took this as an opportunity to learn more about ORMs. In terms of pagination and more dynamic querying I used [Graphene Relay](https://docs.graphene-python.org/en/latest/relay/) and [django-filters](https://django-filter.readthedocs.io/en/master/). 

However, the fact that I had to implement everything made the whole process extremely time consuming. For example it took me about two weeks to figure out a proper way of implementing GraphQL subscriptions, and after that I realized the default GraphQL django view didn't even support subscriptions so I had to change to using [GraphQL playgroud](https://github.com/jaydenwindle/django-graphql-playground). This is why I switched to NodeJS for my current project.

I'm using prisma for my graphql endpoint. To be honest after such a long period of time working with Django and Graphene, I was quite impressed by how powerful and simple prisma was. All you have to do is design your graphql types and deploy it to a prisma docker service. The prisma service then generates all the necessary CRUD (create read update delete) mutations along with fully functional subscriptions to test on. 

With Prisma handling all the basics I need for my graphql server, I use an additional layer of NodeJS server running [graphql-yoga](https://github.com/prisma/graphql-yoga) and connect it to my prisma server with [prisma-binding](https://github.com/prisma/prisma-binding). Adding an additional layer of GraphQL gives me full control over what I want to do when any query or mutation fires. With this layer I'm able to add user authentication.

For the frontend, I currently use React since I find React very intuitive and natural. I use [Apollo Boost](https://github.com/apollographql/apollo-client/tree/master/packages/apollo-boost) and [React Apollo](https://github.com/apollographql/react-apollo) to query my backend server. I haven't looked into VueJS yet, but I'm pretty sure apollo has VueJS support.

That pretty much sums up my opinion and experience with GraphQL! Feel free to ask me any questions!

**Comment by gotexis** [comment]
Thanks for your generous sharing of opinion! I will research some more soon, but just to quickly recap what I have learned today, Prisma seems really a magical tool. What I am currently doing is making a code generator which takes a Django schema, and generate Grapheme schema, test data, Apollo client code, mutatuions, a VueX store (similar to Redux) and a Vue CRUD Frontend...

**Comment by dvfcfbgv** [comment]
Nice. Good luck with your project! Ask me anything if you need help!

**Comment by SmileyChris** [comment]
Django v2+ compatible version merged to master!

**Comment by aliscie** [comment]
> I switched to using https://github.com/datadvance/DjangoChannelsGraphqlWs because graphql-ws wasn't working for me. Note that DjangoChannelsGraphqlWs doesn't work for python 3.6 so what I did was I modified the source code.

Can you share your repo so we can clone it
